<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>ErrorString</name>
    <message>
        <location filename="../../Functions/ErrorString.py" line="9"/>
        <source>LLM config invalid. Please set it in the configuration interface:</source>
        <translation>LLM 配置无效，请检查相关配置：</translation>
    </message>
    <message>
        <location filename="../../Functions/ErrorString.py" line="12"/>
        <source>No valid LLM name was found. Please set it in the configuration interface.</source>
        <translation>LLM 模型名称无效，请在配置页面设置正确的名称。</translation>
    </message>
    <message>
        <location filename="../../Functions/ErrorString.py" line="15"/>
        <source>No valid LLM API was found. Please set it in the configuration interface.</source>
        <translation>LLM 密钥无效，请在配置页面设置正确的密钥。</translation>
    </message>
    <message>
        <location filename="../../Functions/ErrorString.py" line="20"/>
        <source>No valid LLM URL was found. Please set it in the configuration interface.</source>
        <translation>LLM 代理 URL 无效，请在配置页面设置正确的代理。</translation>
    </message>
</context>
</TS>
